// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaEryU0yJD0FAESqMdkCrG6oZtZFIPts',
    appId: '1:906585886866:web:c998fba85bccc4025e964b',
    messagingSenderId: '906585886866',
    projectId: 'grih-sajja',
    authDomain: 'grih-sajja.firebaseapp.com',
    storageBucket: 'grih-sajja.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMqsHnJ4UK_waiq8Rwn8qlv9jfDcxza0',
    appId: '1:906585886866:android:98d568999b233d585e964b',
    messagingSenderId: '906585886866',
    projectId: 'grih-sajja',
    storageBucket: 'grih-sajja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApZTKohVY12ei4FiARf0qPku7PiIHNGk',
    appId: '1:906585886866:ios:86e0869b1dc0f3855e964b',
    messagingSenderId: '906585886866',
    projectId: 'grih-sajja',
    storageBucket: 'grih-sajja.appspot.com',
    androidClientId: '906585886866-f1h6pd56ebtbtk7rsc56e1sm8oih00og.apps.googleusercontent.com',
    iosClientId: '906585886866-fanj2ckl3c97b1ni9qdmekehrd2vbt7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApZTKohVY12ei4FiARf0qPku7PiIHNGk',
    appId: '1:906585886866:ios:cbb74cad4ab551ac5e964b',
    messagingSenderId: '906585886866',
    projectId: 'grih-sajja',
    storageBucket: 'grih-sajja.appspot.com',
    androidClientId: '906585886866-f1h6pd56ebtbtk7rsc56e1sm8oih00og.apps.googleusercontent.com',
    iosClientId: '906585886866-09ffg0n2o8m5id4ploi1geftpmseepf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
